/*
        
        1) Create function testMe that creates 3 variables and returns their product
        2) Create function AI that respond "hi" if the parameter is "hello", "I cannot understand" otherwise
        3) Create function tripleSum that receives 3 numbers and returns the product of them
        4) Create function factorial that calculates the factorial of the given param
        5) Create function calculator with 3 params, two numbers (param1 and param2) and a sign between "+","-","*","/". Return the operation between param1 and param2
        6) Create function absolute that returns the absolute value of the parameter (es.: p = 1 returns 1, p = -27 returns 27)
        7) Create function fizzBuzz that returns fizz if param is multiple of 3, buzz if multiple of 7, fizzbuzz if multiple of 3 and 7. Otherwise returns the same number
        8) Create function positive that returns true if the params is greater than 0
        9) Create function transform that receives a number between 0 and 9 and returns a string containing the number (ex.: 0 returns "zero", 1 returns "one")
        10) Create function sum that receives an array as parameter and return the sum of the elements (only numerical ones)
        11) Create function min that receives an array and returns the minumum value in the array
        12) Create function arrayFi that receives an object and trasforms it in an array. Example: arrayFi({ name: "John", surname: "Doe"}) returns [ "name", "john", "surname", "Doe"]
        13) Create function objectyFi that revert the array generated by arrayFi into and object
        14) Create function revertArray that revert the elements into an array
        15) Create function swappy that receives 2 positions and swap them into the array. Example: array = [ 1, 2, 3, 4]. Swappy(0, 3) ==> [3, 2, 1, 4]

        */

/* Solution 1 */
function testMe(f1,f2,f3) {
    let factorA = f1
    let factorB = f2
    let factorC = f3
    let result = factorA * factorB * factorC
    return result
}

function testMe(f1,f2,f3) {
    console.log("The product is", f1 * f2 * f3)
}

/* Solution 2 */
function AI(s) {
    if (s === "Hello")
        console.log("hi")
    else
        console.log("I cannot understand")
}

/* Solution 3 */
function tripleSum(f1,f2,f3) {
    let result = f1 * f2 * f3
    return result
}
/* Solution 4 */
function factorial(n){
    let total = 1;
    for(let i=n; i > 0; i--){
        total = total * i
}
   return total
}

/* Solution 5 */
function calculator(a,p,b) {
    if(p == "+")
        return (a+b)
    if(p == "-")
        return (a-b)
    if(p == "*")
        return (a*b)
    if(p == "/")
        return (a/b)
    else
        return ("I don't know")
}

/* Solution 6 */
function absolute(n){
    if(n >= 0)
        return n
    else
        return n * (-1)
}

/* Solution 7 */
function fizzBuzz(n){
    if(n%3 == 0 && n%7 == 0)
        return "fizzbuzz"
    if(n%3 == 0)
        return "fizz"
    if(n%7 == 0)
        return "buzz"
    else 
        return n
}

/* Solution 8 */
function positive(n){
    if(n > 0)
        return true
    else
        return "I don't know"
}

/* Solution 9 
    Create function transform that receives a number between 0 and 9 and returns a string containing the number (ex.: 0 returns "zero", 1 returns "one")
*/
function transform(i){
        let givename = ["zero","one", "two","three","four","five","six","seven","eight","nine"]
        return givename[i]
    }

/* Solution 10
Create function sum that receives an array as parameter and return the sum of the elements (only numerical ones)
*/

            /*First Step */
function sum(names){
    let total = 0
    if (isNaN(names[i]) == true)
        for(i = 0; i < names.length; i++){
                total = total + names[i];
        }
    return total
}

            /* Final Solution 10 */
function sum(names){
    let total = 0;
    for (let i in names){
        if(isNaN(names[i]) == false){
            total = total + names[i];
        }
        else {
            console.log("Non è un numero")
        }
    }
    return total;
}
